{% set version = "2.11.4" %}

package:
  name: plumbing
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/plumbing/plumbing-{{ version }}.tar.gz
  sha256: 1cacd04ba80df9e6a9224e91581dc65558cfbcb75491e4adf4e66a5ca4aac9f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - autopaths >=1.6.2
    - pandas
    - retry
    - requests
    - rich
    - tzlocal
    - brewer2mpl

test:
  imports:
    - plumbing
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: http://github.com/xapple/plumbing/
  summary: 'Helps with plumbing-type programing in python.'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xapple
